version: "3"

volumes:
  couch_db:

services:
  couch_db:
    image: "couchdb:3"
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=pipdepgraph
      - COUCHDB_PASSWORD=pipdepgraph
    volumes:
      - couch_db:/opt/couchdb/data
      - ./couchdb_local.ini:/opt/couchdb/etc/local.ini
